### ISSUE TITLE
Tipagem de retorno

### ISSUE THREAD

**Issue by telavita-dev** [TiagoOliverDev/backend_telavita#34]
Percebi que as docstrings contém o tipo a ser retornado porém o próprio método não:

https://github.com/TiagoOliverDev/backend_telavita/blob/12d5c886f2c8e9f5da5197d13e0ed481153422d6/app/repositories/employee_repository.py#L137

Sendo assim, utilizando o exemplo acima, gostaria de entender o que o motivou a não tipar o retorno do método, apenas a docstring.

---
Utilizando outro método como exemplo, podemos perceber que a docstring diz que é retornado um _booleano_ porém o método também pode retornar _None_, sendo assim gostaria de entender o racional por trás da decisão.

https://github.com/TiagoOliverDev/backend_telavita/blob/12d5c886f2c8e9f5da5197d13e0ed481153422d6/app/repositories/employee_repository.py#L46

**Comment by TiagoOliverDev** [comment]
Costume de desenvolver métodos pelas empresas aonde passei sem colocar o type do retorno dela, acabei esquecendo de alocar no próprio método no teste. Ainda iria tirar um tempo pra ver esses pontos de melhoria de código mas chegou ao tempo limite do teste dai acabei não subindo mais commits.
